# Generated by Django 5.1.4 on 2024-12-30 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra_venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libros/')),
                ('condicion', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=50)),
                ('categoria', models.CharField(choices=[('Ficción', 'Ficción'), ('No Ficción', 'No Ficción'), ('Fantasía', 'Fantasía'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Romance', 'Romance'), ('Misterio', 'Misterio'), ('Historia', 'Historia'), ('Biografía', 'Biografía'), ('Infantil', 'Infantil'), ('Autoayuda', 'Autoayuda'), ('Otros', 'Otros')], default='Otro', max_length=50)),
                ('vendido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_vendidos', to='Compra_venta.usuario')),
            ],
        ),
    ]
