# Generated by Django 5.1.4 on 2025-01-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra_venta', '0002_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_encuentro', models.CharField(max_length=255)),
                ('fecha_encuentro', models.DateField()),
                ('hora_encuentro', models.TimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada')], default='Pendiente', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compradas', to='Compra_venta.usuario')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Compra_venta.libro')),
            ],
        ),
    ]
