# Generated by Django 5.1.4 on 2025-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra_venta', '0004_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='en_proceso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('Ficción', 'Ficción'), ('No Ficción', 'No Ficción'), ('Fantasía', 'Fantasía'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Romance', 'Romance'), ('Misterio', 'Misterio'), ('Historia', 'Historia'), ('Biografía', 'Biografía'), ('Infantil', 'Infantil'), ('Autoayuda', 'Autoayuda'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
    ]
