# Generated by Django 5.1.4 on 2025-01-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra_venta', '0005_libro_en_proceso_alter_libro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
